/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./src/components/AdminPannel/AccountManagement/AccountList.vue')['default']
    AddAccount: typeof import('./src/components/AdminPannel/AccountManagement/AddAccount.vue')['default']
    AnnounceDialog: typeof import('./src/components/UserPannel/announceDialog.vue')['default']
    Aria2ConfigDialog: typeof import('./src/components/UserPannel/aria2ConfigDialog.vue')['default']
    ChangeConfig: typeof import('./src/components/AdminPannel/ChangeConfig.vue')['default']
    ChangeMailConfig: typeof import('./src/components/AdminPannel/ChangeMailConfig.vue')['default']
    ChangeUserInfo: typeof import('./src/components/AdminPannel/ChangeUserInfo.vue')['default']
    DownloadDialog: typeof import('./src/components/UserPannel/downloadDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    GetFileListForm: typeof import('./src/components/UserPannel/getFileListForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowFileList: typeof import('./src/components/UserPannel/showFileList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
